[package]
name = "rudisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
walkdir = "2"
structopt = "0.3.26"
rayon = "1.5.3"
pretty-bytes = "0.2.2"
